# Generated by Django 5.1.6 on 2025-02-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_book_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('penulis', models.CharField(max_length=255)),
                ('tahun', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('file_pdf', models.FileField(upload_to='pdfs/')),
                ('images', models.JSONField(default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
